### ISSUE TITLE
KDE's wallpaper "set" doesn't work

### ISSUE THREAD

**Issue by z3ntu** [bharadwaj-raju/libdesktop#1]
```
command = """
qdbus org.kde.plasmashell /PlasmaShell org.kde.PlasmaShell.evaluateScript '
    var allDesktops = desktops();
    print (allDesktops);
    for (i=0;i<allDesktops.length;i++) {{
        d = allDesktops[i];
        d.wallpaperPlugin = "org.kde.image";
        d.currentConfigGroup = Array("Wallpaper",
                                     "org.kde.image",
                                     "General");
        d.writeConfig("Image", "file:///{save_location}")
    }}
'
"""
os.system(command.format(save_location=FILELOCATION))
```

works though.

Additionally I have created a package for easy installation on Arch Linux: https://aur.archlinux.org/packages/python-libdesktop-git/

**Comment by bharadwaj-raju** [comment]
Thanks, for both the package and the correction. Finally, it works on KDE!

I'll be updating the code now. Thanks!

**Comment by bharadwaj-raju** [comment]
Commited.

I'll search for a similar way for `get()`

**Comment by bharadwaj-raju** [comment]
@z3ntu Do you know of a way to do this but for `get()`?

I've tried

```
qdbus org.kde.plasmashell /PlasmaShell org.kde.PlasmaShell.evaluateScript '                                                                                
    var allDesktops = desktops();
    print (allDesktops);
    for (i=0;i<allDesktops.length;i++) {{
        d = allDesktops[i];
        d.wallpaperPlugin = "org.kde.image";
        d.currentConfigGroup = Array("Wallpaper",
                                     "org.kde.image",
                                     "General");
        print(d.readConfig("Image", "default if image not found"))
}}
'
```

(which _should_ work according to KDE's Plasma scripting docs, but doesn't)

**Comment by z3ntu** [comment]
Can you give me the link to the docs please?

**Comment by bharadwaj-raju** [comment]
Here: https://userbase.kde.org/KDE_System_Administration/PlasmaTwoDesktopScripting

**Comment by bharadwaj-raju** [comment]
I've also tried `qdbus`'s `--literal` option, which is supposed to "print replies literally". `dbus-send` has a `--print-reply` option too, I'll try using that.

**Comment by z3ntu** [comment]
You can open the "Desktop Shell Scripting Console" with ~~`qdbus org.kde.plasmashell /PlasmaShell loadScriptInInteractiveConsole ''`~~ `qdbus org.kde.plasmashell /PlasmaShell showInteractiveConsole` where you can run your code and it works there. But I don't know how to get the `print` methods to go to `stdout`...

**EDIT**: Better command

**Comment by bharadwaj-raju** [comment]
Yes, I've tried it — works there. Now I just have to find a way for DBUS to return stdout.

**Comment by z3ntu** [comment]
Apparently it can work with C(++)... https://bugs.kde.org/show_bug.cgi?id=238817#c5

**Comment by bharadwaj-raju** [comment]
Yes! Problem solved:

The wallpaper path is located in a file, too:

`~/.config/plasma-org.kde.plasma.desktop-appletsrc`:

```
...
[Containments][8][Wallpaper][org.kde.image][General]
Image=file:///home/bharadwaj/Pictures/DesktopWallpapers/13.png
height=900
width=1440
...
```
