### ISSUE TITLE
setup.py doesn't install the dialog module

### ISSUE THREAD

**Issue by z3ntu** [bharadwaj-raju/libdesktop#2]
```
>>> import libdesktop.wallpaper
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/usr/lib/python3.5/site-packages/libdesktop/__init__.py", line 10, in <module>
    from . import dialog
ImportError: cannot import name 'dialog'
```

**Comment by z3ntu** [comment]
869e32d8957e395487a9b5e3a957304c14b79e94 broke it (17530dd still worked)

**Comment by bharadwaj-raju** [comment]
Interesting. It works when you are in the project root and import it, but fails elsewhere.

**Comment by bharadwaj-raju** [comment]
For some reason `dialog/` is not copied over when doing `setup.py`

**Comment by z3ntu** [comment]
Weird...

**Comment by bharadwaj-raju** [comment]
I've found the solution. You have to manually add submodules to `setup.py`

Anyway, it's done now, and committed. Try again.

**Comment by z3ntu** [comment]
Yes, works again. Thanks!
